[package]
name = "automated_teller_machine"
version = "0.1.0"
authors = ["Paolo D'Incau <paolo.dincau@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
