[package]
name = "automated_teller_machine"
version = "0.1.0"
authors = ["Paolo D'Incau"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
claim = "0.5.0"
strum = "0.21.0"
strum_macros = "0.21.1"
thiserror = "1.0.26"
